# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'RAPlayer' do
	pod 'SDWebImage'
	pod 'Pulley'
end
